# Translations template for oslo.vmware.
# Copyright (C) 2014 ORGANIZATION
# This file is distributed under the same license as the oslo.vmware
# project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2014.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: oslo.vmware 0.3.22.gc4e0294\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2014-06-05 22:50+0200\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"

#: oslo/vmware/api.py:91
#, python-format
msgid ""
"Exception which is in the suggested list of exceptions occurred while "
"invoking function: %s."
msgstr ""

#: oslo/vmware/api.py:98
#, python-format
msgid ""
"Cannot retry upon suggested exception since retry count (%(retry_count)d)"
" reached max retry count (%(max_retry_count)d)."
msgstr ""

#: oslo/vmware/api.py:109
#, python-format
msgid ""
"Exception which is not in the suggested list of exceptions occurred while"
" invoking %s."
msgstr ""

#: oslo/vmware/api.py:212
#, python-format
msgid "Successfully established new session; session ID is %s."
msgstr ""

#: oslo/vmware/api.py:219
#, python-format
msgid "Terminating the previous session with ID = %s"
msgstr ""

#: oslo/vmware/api.py:229
#, python-format
msgid "Error occurred while terminating the previous session with ID = %s."
msgstr ""

#: oslo/vmware/api.py:241
#, python-format
msgid "Logging out and terminating the current session with ID = %s."
msgstr ""

#: oslo/vmware/api.py:248
#, python-format
msgid ""
"Error occurred while logging out and terminating the current session with"
" ID = %s."
msgstr ""

#: oslo/vmware/api.py:301
#, python-format
msgid ""
"Current session: %(session)s is inactive; re-creating the session while "
"invoking method %(module)s.%(method)s."
msgstr ""

#: oslo/vmware/api.py:322
#, python-format
msgid ""
"Re-creating session due to connection problems while invoking method "
"%(module)s.%(method)s."
msgstr ""

#: oslo/vmware/api.py:347
#, python-format
msgid "Error occurred while checking whether the current session: %s is active."
msgstr ""

#: oslo/vmware/api.py:388
#, python-format
msgid "Error occurred while reading info of task: %s."
msgstr ""

#: oslo/vmware/api.py:402
#, python-format
msgid "Task: %(task)s failed with error: %(error)s."
msgstr ""

#: oslo/vmware/api.py:442
#, python-format
msgid "Error occurred while checking state of lease: %s."
msgstr ""

#: oslo/vmware/api.py:456
#, python-format
msgid "Lease: %(lease)s is in error state. Details: %(error_msg)s."
msgstr ""

#: oslo/vmware/api.py:463
#, python-format
msgid "Unknown state: %(state)s for lease: %(lease)s."
msgstr ""

#: oslo/vmware/api.py:477
#, python-format
msgid "Error occurred while reading error message for lease: %s."
msgstr ""

#: oslo/vmware/exceptions.py:48
msgid "exception_summary must not be a list"
msgstr ""

#: oslo/vmware/exceptions.py:81
msgid "fault_list must be a list"
msgstr ""

#: oslo/vmware/exceptions.py:107
msgid "An unknown exception occurred."
msgstr ""

#: oslo/vmware/exceptions.py:119
msgid "Exception in string format operation"
msgstr ""

#: oslo/vmware/exceptions.py:132
msgid "VMware Driver configuration fault."
msgstr ""

#: oslo/vmware/exceptions.py:136
msgid "No default value for use_linked_clone found."
msgstr ""

#: oslo/vmware/exceptions.py:140
#, python-format
msgid "Missing parameter : %(param)s"
msgstr ""

#: oslo/vmware/exceptions.py:144
msgid "Resource already exists."
msgstr ""

#: oslo/vmware/exceptions.py:149
msgid "Cannot delete file."
msgstr ""

#: oslo/vmware/exceptions.py:154
msgid "File already exists."
msgstr ""

#: oslo/vmware/exceptions.py:159
msgid "File fault."
msgstr ""

#: oslo/vmware/exceptions.py:164
msgid "File locked."
msgstr ""

#: oslo/vmware/exceptions.py:169
msgid "File not found."
msgstr ""

#: oslo/vmware/exceptions.py:174
msgid "Invalid power state."
msgstr ""

#: oslo/vmware/exceptions.py:179
msgid "Invalid property."
msgstr ""

#: oslo/vmware/exceptions.py:184
msgid "No Permission."
msgstr ""

#: oslo/vmware/exceptions.py:189
msgid "Not Authenticated."
msgstr ""

#: oslo/vmware/image_transfer.py:170
#, python-format
msgid "Image: %s is in killed state."
msgstr ""

#: oslo/vmware/image_transfer.py:184
#, python-format
msgid "Image: %(image)s is in unknown state: %(state)s."
msgstr ""

#: oslo/vmware/image_transfer.py:192
#, python-format
msgid "Error occurred while writing image: %s"
msgstr ""

#: oslo/vmware/image_transfer.py:277
msgid "Error occurred during file read-write task."
msgstr ""

#: oslo/vmware/image_transfer.py:364
msgid "No image destination given."
msgstr ""

#: oslo/vmware/image_transfer.py:381
#, python-format
msgid ""
"Error occurred during image transfer with reader: %(reader)s and writer: "
"%(writer)s"
msgstr ""

#: oslo/vmware/rw_handles.py:64
msgid "Error occurred while closing the file handle"
msgstr ""

#: oslo/vmware/rw_handles.py:142
msgid "Could not retrieve VMDK URL from lease info."
msgstr ""

#: oslo/vmware/rw_handles.py:192 oslo/vmware/rw_handles.py:335
#, python-format
msgid "Invalid scheme: %s."
msgstr ""

#: oslo/vmware/rw_handles.py:206
#, python-format
msgid ""
"Error occurred while creating HTTP connection to write to file with URL ="
" %s."
msgstr ""

#: oslo/vmware/rw_handles.py:221 oslo/vmware/rw_handles.py:375
#, python-format
msgid "Connection error occurred while writing data to %s."
msgstr ""

#: oslo/vmware/rw_handles.py:229 oslo/vmware/rw_handles.py:383
#, python-format
msgid "Error occurred while writing data to %s."
msgstr ""

#: oslo/vmware/rw_handles.py:240
msgid "Error occurred while reading the HTTP response."
msgstr ""

#: oslo/vmware/rw_handles.py:354
#, python-format
msgid ""
"Error occurred while creating HTTP connection to write to VMDK file with "
"URL = %s."
msgstr ""

#: oslo/vmware/rw_handles.py:412
#, python-format
msgid ""
"Error occurred while updating the write progress of VMDK file with URL = "
"%s."
msgstr ""

#: oslo/vmware/rw_handles.py:445 oslo/vmware/rw_handles.py:607
#, python-format
msgid "Error occurred while releasing the lease for %s."
msgstr ""

#: oslo/vmware/rw_handles.py:519
#, python-format
msgid "Error occurred while opening URL: %s for reading."
msgstr ""

#: oslo/vmware/rw_handles.py:545
#, python-format
msgid "Error occurred while reading data from %s."
msgstr ""

#: oslo/vmware/rw_handles.py:574
#, python-format
msgid ""
"Error occurred while updating the read progress of VMDK file with URL = "
"%s."
msgstr ""

#: oslo/vmware/vim.py:150
#, python-format
msgid "Faults %s found in RetrievePropertiesEx API response."
msgstr ""

#: oslo/vmware/vim.py:154
msgid "Error occurred while calling RetrievePropertiesEx."
msgstr ""

#: oslo/vmware/vim.py:216
#, python-format
msgid "No such SOAP method %s."
msgstr ""

#: oslo/vmware/vim.py:222
#, python-format
msgid "httplib error in %s."
msgstr ""

#: oslo/vmware/vim.py:226
#, python-format
msgid "urllib2 error in %s."
msgstr ""

#: oslo/vmware/vim.py:237
#, python-format
msgid "Socket error in %s."
msgstr ""

#: oslo/vmware/vim.py:242
#, python-format
msgid "Type error in %s."
msgstr ""

#: oslo/vmware/vim.py:245
#, python-format
msgid "Exception in %s."
msgstr ""

#: oslo/vmware/common/loopingcall.py:82
#, python-format
msgid "task run outlasted interval by %s sec"
msgstr ""

#: oslo/vmware/common/loopingcall.py:89
msgid "in fixed duration looping call"
msgstr ""

#: oslo/vmware/common/loopingcall.py:136
msgid "in dynamic looping call"
msgstr ""

#: oslo/vmware/openstack/common/gettextutils.py:297
msgid "Message objects do not support addition."
msgstr ""

#: oslo/vmware/openstack/common/gettextutils.py:306
msgid ""
"Message objects do not support str() because they may contain non-ascii "
"characters. Please use unicode() or translate() instead."
msgstr ""

